version: "3"

services:
  azure-smtp-relay:
    build: .
    container_name: azure-smtp-relay
    image: azure-smtp-relay:latest
    ports:
      - 1025:1025/tcp
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
